### PR TITLE
Added feature to build using an Existing available EIP (Elastic IP)

### PR DESCRIPTION
**Pull request by niklas-nielsen**
Added the possibility to create an image build using an existing available EIP instead of allocating a new one.

Why this feature:
Currently it's possible to build using existing network infrastructure such as VPC and Vswitch and security groups, we are using this - yet we are also using Cloud firewall and here we need some custom rules for image build VM's to work.
By having a pool of Known before IP addresses we can apply the firewall rules to them, then we just need to use any available EIP from that pool during the build process.

### CODE REVIEW

**Review by daniel-sanchez-maersk — CHANGES_REQUESTED** [review]
Required proper indentation to match code styling.

**Review by nywilken — APPROVED** [review]
This looks good to me. There are a few missing generated files that can be fixed on merge. Thanks for the addition.

**Comment by niklas-nielsen** [comment]
@nywilken Do you know when the next release version will be made? 👍 
And Is there anything i can do / help out with?

**Comment by nywilken** [comment]
> @nywilken Do you know when the next release version will be made? 👍 And Is there anything i can do / help out with?

Hi @niklas-nielsen thanks for the bump. We generally release plugins on Tuesday. I missed this one last week and will release later today.

**Comment by nywilken** [comment]
This feature has been released in [v1.1.1](https://github.com/hashicorp/packer-plugin-alicloud/releases/tag/v1.1.1)

**Pull request merged**
